Repository msarmi9/Sparkle, pull requests merged in 2020-04, with the labels that each got.

#64 converted preprocessing functions to python/pandas variant
  sparkle/scripts/preprocess.py
Labels: enhancement

#84 Workflows
  .github/.keep
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  .gitignore
  docs/requirements.txt
  setup.py
Labels: enhancement

#85 add configs for readthedocs build env
  .readthedocs.yml
Labels: bug

#91 add flask reqs
  docs/requirements.txt
Labels: bug

#88 Mobile
  mobile/.gitignore
  mobile/Playground.playground/Contents.swift
  mobile/Playground.playground/alamo_workspace.xcworkspace/contents.xcworkspacedata
  mobile/Playground.playground/contents.xcplayground
  mobile/Playground.playground/playground.xcworkspace/contents.xcworkspacedata
  mobile/Playground.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  mobile/Playground.playground/playground_workspace.xcworkspace/contents.xcworkspacedata
  mobile/Podfile
  mobile/instructions.md
  mobile/mobile WatchKit App/Assets.xcassets/AppIcon.appiconset/Contents.json
  mobile/mobile WatchKit App/Assets.xcassets/Contents.json
  mobile/mobile WatchKit App/Base.lproj/Interface.storyboard
  mobile/mobile WatchKit App/Info.plist
  mobile/mobile WatchKit Extension/Assets.xcassets/Complication.complicationset/Circular.imageset/Contents.json
  mobile/mobile WatchKit Extension/Assets.xcassets/Complication.complicationset/Contents.json
  mobile/mobile WatchKit Extension/Assets.xcassets/Complication.complicationset/Extra Large.imageset/Contents.json
  mobile/mobile WatchKit Extension/Assets.xcassets/Complication.complicationset/Graphic Bezel.imageset/Contents.json
  mobile/mobile WatchKit Extension/Assets.xcassets/Complication.complicationset/Graphic Circular.imageset/Contents.json
  mobile/mobile WatchKit Extension/Assets.xcassets/Complication.complicationset/Graphic Corner.imageset/Contents.json
  mobile/mobile WatchKit Extension/Assets.xcassets/Complication.complicationset/Graphic Large Rectangular.imageset/Contents.json
  mobile/mobile WatchKit Extension/Assets.xcassets/Complication.complicationset/Modular.imageset/Contents.json
  mobile/mobile WatchKit Extension/Assets.xcassets/Complication.complicationset/Utilitarian.imageset/Contents.json
  mobile/mobile WatchKit Extension/Assets.xcassets/Contents.json
  mobile/mobile WatchKit Extension/ComplicationController.swift
  mobile/mobile WatchKit Extension/ContentView.swift
  mobile/mobile WatchKit Extension/ExtensionDelegate.swift
  mobile/mobile WatchKit Extension/HostingController.swift
  mobile/mobile WatchKit Extension/Info.plist
  mobile/mobile WatchKit Extension/MotionManager.swift
  mobile/mobile WatchKit Extension/NotificationController.swift
  mobile/mobile WatchKit Extension/NotificationView.swift
  mobile/mobile WatchKit Extension/Preview Content/Preview Assets.xcassets/Contents.json
  mobile/mobile WatchKit Extension/PushNotificationPayload.apns
  mobile/mobile WatchKit Extension/SensorView.swift
  mobile/mobile.xcodeproj/project.pbxproj
  mobile/mobile.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  mobile/mobile.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  mobile/mobile.xcworkspace/contents.xcworkspacedata
  mobile/mobile.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  mobile/mobile/AppDelegate.swift
  mobile/mobile/Assets.xcassets/AppIcon.appiconset/Contents.json
  mobile/mobile/Assets.xcassets/Contents.json
  mobile/mobile/Base.lproj/LaunchScreen.storyboard
  mobile/mobile/ContentView.swift
  mobile/mobile/Info.plist
  mobile/mobile/Preview Content/Preview Assets.xcassets/Contents.json
  mobile/mobile/SceneDelegate.swift
  mobile/mobile/SensorLogView.swift
Labels: feature, iOS, watchOS

#102 Enhance patient profile display, add docstrings
  app/classes.py
  app/routes.py
  app/templates/index.html
  app/templates/patient_profile.html
Labels: enhancement

#103 Host docs via gh-pages
  .github/workflows/docs.yml
  .readthedocs.yml
  README.md
Labels: documentation

#112 Workflows
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  app/routes.py
Labels: enhancement

#113 trigger docs/linter workflows on PRs only
  .github/workflows/docs.yml
  .github/workflows/lint.yml
Labels: enhancement

#110 use pandas v1.0.3
  requirements.txt
Labels: bug

#123 Fix prescription adherence for one patient, no prescriptions case
  app/routes.py
Labels: bug
