Repository msarmi9/Sparkle, pull requests merged in 2020-06, with the labels that each got.

#188 Postgres docker setup
  .dockerignore
  Dockerfile
  app/__init__.py
  app/config.py
  app/models/medication.py
  app/templates/prescriptions/add_prescription.html
  app/views/prescriptions.py
  docker-compose.yml
  requirements.txt
  tests/conftest.py
Labels: web

#189 CD workflow
  .github/workflows/build.yml
  .github/workflows/test.yml
Labels: feature

#190 Fix deploy.yml
  .github/workflows/build.yml
Labels: bug

#193 Workflows
  .github/workflows/build.yml
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/test.yml
  app/models/__init__.py
  app/models/forms.py
  app/models/persons.py
  app/utils/__init__.py
  app/views/__init__.py
  docs/requirements.txt
  docs/source/app.api.rst
  docs/source/app.forms.rst
  docs/source/app.medication.rst
  docs/source/app.models.rst
  docs/source/app.persons.rst
  docs/source/app.routes.rst
  docs/source/app.rst
  docs/source/app.utils.rst
  docs/source/app.views.rst
  docs/source/conf.py
  docs/source/modules.rst
  docs/source/tutorial.rst
  setup.py
  tests/models/test_persons.py
  tests/views/test_auth.py
  tests/views/test_patients.py
Labels: documentation

#194 tag deploys with SHA, label with REF
  .github/workflows/build.yml
Labels: bug

#196 Deploy existing package version if available
  .github/workflows/build.yml
Labels: enhancement

#197 Fixed video size on mobile
  app/templates/home/splash.html
Labels: bug, web

#198 Show video below tagline on homepage
  app/templates/home/splash.html
Labels: web

#199 Update readme
  README.md
  app/templates/home/splash.html
Labels: documentation, enhancement
