Repository msarmi9/Sparkle, pull requests merged in 2020-05, with the labels that each got.

#124 Mobile login
  app/classes.py
  app/routes.py
  mobile/Playground.playground/Contents.swift
  mobile/Playground.playground/alamo_workspace.xcworkspace/contents.xcworkspacedata
  mobile/Playground.playground/contents.xcplayground
  mobile/Playground.playground/playground.xcworkspace/contents.xcworkspacedata
  mobile/Playground.playground/playground.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  mobile/Playground.playground/playground_workspace.xcworkspace/contents.xcworkspacedata
  mobile/mobile WatchKit Extension/ContentView.swift
  mobile/mobile.xcodeproj/project.pbxproj
  mobile/mobile/ContentView.swift
  mobile/mobile/SensorLogView.swift
Labels: iOS, web

#115 add new logo to web app
  app/static/logo.png
  app/templates/index.html
  app/templates/splash.html
Labels: web

#125 added config for static files
  .ebextensions/options.config
Labels: bug, web

#132 Dockerfile
  .dockerignore
  .ebextensions/options.config
  .ebextensions/wsgi.config
  .flaskenv
  .gitignore
  Dockerfile
  app/config.py
  application.py
  docker-compose.yml
  sparkle/scripts/preprocess.py
  sparkle/scripts/sparkle_add_cols.py
Labels: feature

#134 added calendar UI
  app/routes.py
  app/templates/add_prescription.html
  app/templates/index.html
Labels: feature, web

#136 Web refact
  app/__init__.py
  app/classes.py
  app/forms.py
  app/medication.py
  app/persons.py
  app/routes.py
Labels: web

#140 About page
  app/routes.py
  app/static/hand-with-a-pill.png
  app/static/site.webmanifest
  app/templates/about.html
  app/templates/index.html
Labels: enhancement, web

#142 Mobile
  README.md
  docs/images/iOS_app.png
  mobile/mobile WatchKit Extension/Assets.xcassets/logo.imageset/Contents.json
  mobile/mobile WatchKit Extension/Assets.xcassets/logo.imageset/logo.png
  mobile/mobile WatchKit Extension/Assets.xcassets/logo_new.imageset/Contents.json
  mobile/mobile WatchKit Extension/Assets.xcassets/logo_new.imageset/logo_new.png
  mobile/mobile WatchKit Extension/ContentView.swift
  mobile/mobile.xcodeproj/project.pbxproj
  mobile/mobile/Assets.xcassets/ai.imageset/Contents.json
  mobile/mobile/Assets.xcassets/ai.imageset/ai.png
  mobile/mobile/Assets.xcassets/logo.imageset/Contents.json
  mobile/mobile/Assets.xcassets/logo.imageset/logo.png
  mobile/mobile/Assets.xcassets/logo_new.imageset/Contents.json
  mobile/mobile/Assets.xcassets/logo_new.imageset/logo_new.png
  mobile/mobile/Assets.xcassets/sparkleColor.colorset/Contents.json
  mobile/mobile/Assets.xcassets/sparkleColorAccent.colorset/Contents.json
  mobile/mobile/ContentView.swift
  mobile/mobile/Media.xcassets/Color.colorset/Contents.json
  mobile/mobile/Media.xcassets/Contents.json
  mobile/mobile/SceneDelegate.swift
  mobile/mobile/SensorLogView.swift
Labels: feature

#146 Web theme
  app/static/css/sb-admin-2.css
  app/static/css/sb-admin-2.min.css
  app/static/js/demo/chart-area-demo.js
  app/static/js/demo/chart-bar-demo.js
  app/static/js/demo/chart-pie-demo.js
  app/static/js/demo/datatables-demo.js
  app/static/js/sb-admin-2.js
  app/static/js/sb-admin-2.min.js
  app/templates/base.html
  app/templates/patients.html
  app/templates/patients_unprescribed.html
Labels: bug, web

#148 adding favicon icon to mobile apps
  mobile/mobile WatchKit Extension/Assets.xcassets/hand-with-a-pill.imageset/Contents.json
  mobile/mobile WatchKit Extension/Assets.xcassets/hand-with-a-pill.imageset/hand-with-a-pill.png
  mobile/mobile WatchKit Extension/ContentView.swift
  mobile/mobile/Assets.xcassets/hand-with-a-pill.imageset/Contents.json
  mobile/mobile/Assets.xcassets/hand-with-a-pill.imageset/hand-with-a-pill.png
  mobile/mobile/ContentView.swift
Labels: enhancement, iOS, watchOS

#163 Refactor __init__.py via app factory paradigm
  app/__init__.py
  app/models/medication.py
Labels: enhancement, web

#161 Re-add Andy's old test for ``Prescription`` class
  app/models/persons.py
  tests/app/models/test_medication.py
Labels: test

#165 Web api tests
  .github/workflows/lint.yml
  app/__init__.py
  app/config.py
  app/models/persons.py
  app/static/site.webmanifest
  app/static/vendor/bootstrap/css/bootstrap-grid.css
  app/static/vendor/bootstrap/css/bootstrap-grid.css.map
  app/static/vendor/bootstrap/css/bootstrap-grid.min.css
  app/static/vendor/bootstrap/css/bootstrap-grid.min.css.map
  app/static/vendor/bootstrap/css/bootstrap-reboot.css
  app/static/vendor/bootstrap/css/bootstrap-reboot.css.map
  app/static/vendor/bootstrap/css/bootstrap-reboot.min.css
  app/static/vendor/bootstrap/css/bootstrap-reboot.min.css.map
  app/static/vendor/bootstrap/css/bootstrap.css
  app/static/vendor/bootstrap/css/bootstrap.css.map
  app/static/vendor/bootstrap/css/bootstrap.min.css
  app/static/vendor/bootstrap/css/bootstrap.min.css.map
  app/static/vendor/bootstrap/js/bootstrap.bundle.js.map
  app/static/vendor/bootstrap/js/bootstrap.bundle.min.js
  app/static/vendor/bootstrap/js/bootstrap.bundle.min.js.map
  app/static/vendor/bootstrap/js/bootstrap.js.map
  app/static/vendor/bootstrap/js/bootstrap.min.js
  app/static/vendor/bootstrap/js/bootstrap.min.js.map
  app/static/vendor/chart.js/Chart.bundle.js
  app/static/vendor/chart.js/Chart.js
  app/static/vendor/datatables/dataTables.bootstrap4.js
  app/static/vendor/datatables/jquery.dataTables.js
  app/static/vendor/fontawesome-free/css/all.min.css
  app/static/vendor/fontawesome-free/css/brands.min.css
  app/static/vendor/fontawesome-free/css/fontawesome.min.css
  app/static/vendor/fontawesome-free/css/regular.min.css
  app/static/vendor/fontawesome-free/css/solid.min.css
  app/static/vendor/fontawesome-free/css/svg-with-js.min.css
  app/static/vendor/fontawesome-free/css/v4-shims.min.css
  app/static/vendor/fontawesome-free/webfonts/fa-brands-400.svg
  app/static/vendor/fontawesome-free/webfonts/fa-regular-400.svg
  app/static/vendor/fontawesome-free/webfonts/fa-solid-900.svg
  app/static/vendor/jquery-easing/jquery.easing.min.js
  app/static/vendor/jquery/jquery.min.map
  app/static/vendor/jquery/jquery.slim.min.map
  setup.py
  tests/api/test_mobile.py
  tests/app/models/test_medication.py
  tests/conftest.py
  tests/data/2020-04-27_21_00_19_2.csv
  tests/modeling/test_modeling.py
  tests/models/test_medication.py
  tests/models/test_persons.py
Labels: test

#167 Issue166/fix db setup
  app/__init__.py
  app/adherence.py
  app/api/mobile.py
  app/config.py
  app/models/forms.py
  app/models/medication.py
  app/models/persons.py
  app/ploting.py
  app/views/auth.py
  app/views/dashboard.py
  app/views/home.py
  app/views/patients.py
  app/views/prescriptions.py
  tests/api/test_mobile.py
Labels: bug

#168 Add Tests for Views
  app/__init__.py
  app/adherence.py
  app/config.py
  app/models/forms.py
  app/models/medication.py
  app/models/persons.py
  app/ploting.py
  app/views/auth.py
  app/views/dashboard.py
  app/views/home.py
  app/views/patients.py
  app/views/prescriptions.py
  requirements.txt
  tests/api/test_mobile.py
  tests/conftest.py
  tests/models/test_medication.py
  tests/models/test_persons.py
  tests/utils.py
  tests/views/test_auth.py
  tests/views/test_dashboard.py
  tests/views/test_home.py
  tests/views/test_patients.py
  tests/views/test_prescriptions.py
Labels: test

#169 Test adherence
  app/api/mobile.py
  app/models/medication.py
  app/utils/adherence.py
  app/utils/ploting.py
  app/views/dashboard.py
  app/views/prescriptions.py
  modeling/predict.py
  tests/data/2020-04-21_07_51_17_1.csv
  tests/data/2020-04-21_09_11_37_at_rest.csv
  tests/data/README.md
  tests/modeling/test_predict.py
  tests/views/test_prescriptions.py
Labels: test

#171 Web searchbar
  app/static/css/landing-page.min.css
  app/templates/base.html
  app/views/patients.py
  tests/views/test_patients.py
Labels: feature, web

#172 Added video
  README.md
Labels: enhancement

#174 bug fix: add age, weight columns to patient table
  app/models/persons.py
Labels: bug

#175 Make search bar case insensitive
  app/models/forms.py
  app/views/patients.py
Labels: enhancement, web

#177 Apply base template
  app/templates/base.html
  app/templates/dashboard/dashboard.html
  app/templates/patients/add_patient.html
  app/templates/prescriptions/add_prescription.html
  app/utils/ploting.py
Labels: enhancement, web

#176 Tidy html
  app/models/medication.py
  app/static/css/landing-page.min.css
  app/templates/base.html
  app/templates/index.html
  app/templates/patients/patients.html
  app/templates/patients/patients_deviating.html
  app/templates/patients/patients_ontrack.html
  app/templates/patients/patients_unprescribed.html
  app/templates/patients/profile.html
  app/utils/adherence.py
  app/views/patients.py
  app/views/prescriptions.py
  tests/conftest.py
  tests/views/test_patients.py
  tests/views/test_prescriptions.py
Labels: enhancement, web

#178 Cleanup
  app/templates/base.html
  app/templates/index.html
  notebooks/KW-modeling-eda.ipynb
  notebooks/README.md
Labels: chore

#179 add youtube to splash.html, logo redirect to splash.html
  app/templates/base.html
  app/templates/home/splash.html
Labels: enhancement, web
